[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.local]
rpc_url = "${RPC_URL}"
private_key = "${PRIVATE_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
